


CREATE PROCEDURE [dbo].[RO_SP_PRORRATEAR_INTEGRAL_V2]    
(        
    @DESDE DATE,        
    @HASTA DATE,
    @ID_PROCESO INT = NULL  -- ID del proceso para actualizar progreso
) AS        
        
DECLARE @PERIODO [VARCHAR](7);        
SET @PERIODO = CAST(DATEPART(MONTH, @HASTA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, @HASTA) AS VARCHAR);        
        
BEGIN        
    BEGIN TRY
        -- Punto de control: Inicio de creación de tabla temporal
        IF @ID_PROCESO IS NOT NULL
        BEGIN
            EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                @ID_PROCESO = @ID_PROCESO,
                @ESTADO = 'EN_PROCESO',
                @PROGRESO = 35,
                @MENSAJE = 'Creando tabla temporal...';
        END

        --CREAR TABLA TEMPORAL--        
        CREATE TABLE #TABLA_TEMPORAL_PR             
        (        
        [ID] INT,        
        [PERIODO] [VARCHAR](7) COLLATE Modern_Spanish_CI_AI,         
        [MODULO] [VARCHAR](20) COLLATE Modern_Spanish_CI_AI,        
        [COD_AUXILIAR] [VARCHAR](17) COLLATE Modern_Spanish_CI_AI,         
        [FECHA] DATE,        
        [DESC_AUXILIAR] [VARCHAR](40) COLLATE Modern_Spanish_CI_AI,        
        [SECTOR] [VARCHAR](20) COLLATE Modern_Spanish_CI_AI,        
        [COD_CUENTA] [VARCHAR](40) COLLATE Modern_Spanish_CI_AI,        
        [DESC_CUENTA] [VARCHAR](100) COLLATE Modern_Spanish_CI_AI,        
        [SALDO_ORIGEN] [NUMERIC](38, 7),        
        [SALDO_PRORRATEO] [NUMERIC](38, 7),        
        [DESC_LEYENDA] [VARCHAR](100) COLLATE Modern_Spanish_CI_AI,        
        [T_COMP] [VARCHAR](3) COLLATE Latin1_General_BIN,        
        [RAZON_SOCIAL] [VARCHAR](100) COLLATE Modern_Spanish_CI_AI,        
        [PROVEEDOR] [VARCHAR](6) COLLATE Latin1_General_BIN,        
        [N_COMP] [VARCHAR](20) COLLATE Latin1_General_BIN,        
        [IMPUTACIONES][VARCHAR](2) COLLATE Modern_Spanish_CI_AI,        
        [COD_RUBRO] [VARCHAR](8) COLLATE Modern_Spanish_CI_AI,        
        [RUBRO_CONTABLE] [VARCHAR](50) COLLATE Modern_Spanish_CI_AI,        
        [COD_PRORRATEO] [VARCHAR](2) COLLATE Modern_Spanish_CI_AI,        
        [COD_PRORRATEO_2] [VARCHAR](2) COLLATE Modern_Spanish_CI_AI,        
        [DESC_PRORRATEO] [VARCHAR](70) COLLATE Modern_Spanish_CI_AI,        
        [NUM_SUCURSAL] [VARCHAR](3) COLLATE Modern_Spanish_CI_AI,        
        [PRORRATEADO] [BIT],        
        [ID_AA] INT,        
        [AMORTIZAR] [BIT],        
        [AMORTIZADO] [BIT]        
        );

        -- Punto de control: Inicio de insert masivo
        IF @ID_PROCESO IS NOT NULL
        BEGIN
            EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                @ID_PROCESO = @ID_PROCESO,
                @ESTADO = 'EN_PROCESO',
                @PROGRESO = 45,
                @MENSAJE = 'Recopilando registros para prorratear...';
        END
        
        --INSERTA EN LA TABLA TEMPORAL DE PRORRATEOS--        
        INSERT INTO #TABLA_TEMPORAL_PR        
        
        --REGISTROS DE PRORRATEO METODO 1--        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, A.NUM_SUCURSAL, NULL PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '1'        
        AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZADO IS NULL) A        
        WHERE A.EXCLUIR = 0 AND A.ID NOT IN (SELECT DISTINCT(ID) ID FROM RO_T_INTEGRAL_PRORRATEOS)        
        UNION ALL        
        SELECT A.ID, @PERIODO PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, A.NUM_SUCURSAL, NULL PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '1'        
        AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND AMORTIZAR IS NULL) A        
        WHERE A.EXCLUIR = 0 AND A.ID NOT IN (SELECT DISTINCT(ID) ID FROM RO_T_INTEGRAL_PRORRATEOS)        
             
        UNION ALL        
          
        --REGISTROS DE PRORRATEO METODO 2--        
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,         
        CASE WHEN A.COD_PRORRATEO_2 = '4' THEN     
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        ELSE     
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        END SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO, ISNULL(B.NRO_SUCURS, A.NRO_SUCURS) NUM_SUCURSAL, 1 PRORRATEADO, A.ID_AA,        
        A.AMORTIZAR, A.AMORTIZADO FROM        
        (        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,         
        CAST(CAST((A.SALDO*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP,         
        A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,        
        CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,         
        A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS,         
        A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '2'        
        AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO         
        UNION ALL        
        SELECT A.ID, @PERIODO PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,         
        CAST(CAST((A.SALDO*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP,         
        A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,        
        CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,         
        A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS,         
        A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '2'        
        AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        ) A        
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO        
        WHERE A.ID NOT IN (SELECT DISTINCT(ID) ID FROM RO_T_INTEGRAL_PRORRATEOS)        
          
        UNION ALL        
          
        --REGISTROS DE PRORRATEO METODO 3--        
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,         
        CASE WHEN A.COD_PRORRATEO_2 = '4' THEN     
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        ELSE     
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        END SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO, ISNULL(B.NRO_SUCURS, A.NRO_SUCURS) NUM_SUCURSAL, 1 PRORRATEADO, A.ID_AA,        
        A.AMORTIZAR, A.AMORTIZADO FROM        
        (        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,         
        CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,        
        A.DESC_PRORRATEO, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '3'        
        AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        WHERE A.EXCLUIR = 0        
        UNION ALL      
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,         
        CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,        
        A.DESC_PRORRATEO, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '3'        
        AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        WHERE A.EXCLUIR = 0        
        ) A        
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO        
          
        UNION ALL        
          
        --REGISTROS DE PRORRATEO METODO 4--        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, B.NRO_SUCURS,  1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '4'        
        AND FECHA BETWEEN @DESDE AND @HASTA  AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        WHERE A.EXCLUIR = 0        
        UNION ALL        
        SELECT A.ID, @PERIODO PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, B.NRO_SUCURS,  1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '4'        
        AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        WHERE A.EXCLUIR = 0        
          
        UNION ALL        
          
        --PRORRATEO METODO 5--        
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,         
        CASE WHEN A.COD_PRORRATEO_2 = '4' THEN     
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        ELSE     
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        END SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO,         
        ISNULL(B.NRO_SUCURS, A.NRO_SUCURS) NRO_SUCURS, 1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,     
        A.DESC_LEYENDA, A.T_COMP,         
        A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,        
        CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,         
        A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '5'        
        AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        ) A        
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO        
          
        UNION ALL        
          
        --PRORRATEO METODO 7--        
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,         
        CASE WHEN A.COD_PRORRATEO_2 = '4' THEN     
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        ELSE     
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        END SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO,         
        ISNULL(ISNULL(B.NRO_SUCURS, A.NRO_SUCURS_2), A.NRO_SUCURS) NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (        
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO,         
        CASE WHEN A.COD_PRORRATEO_2 = '2' THEN     
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        ELSE     
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))     
        END SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP,         
        A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,     
        CASE WHEN B.NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,         
        A.DESC_PRORRATEO, A.NRO_SUCURS, B.NRO_SUCURS NRO_SUCURS_2, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,     
        A.DESC_LEYENDA, A.T_COMP,         
        A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,        
        CASE WHEN NRO_SUCURS = 0 THEN '2' ELSE '' END COD_PRORRATEO_2,         
        A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '7'        
        AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO        
        ) A        
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO        
        ) A        
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO        
          
        UNION ALL        
          
        --REGISTROS DE PRORRATEO METODO 10--        
        SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,     
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,     
        CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,         
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, B.NRO_SUCURS,  1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM        
        (  
        SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2   
        WHERE COD_PRORRATEO = '10' AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL    
        UNION ALL  
        SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2   
        WHERE COD_PRORRATEO = '10' AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL AND AMORTIZADO IS NULL       
        ) A        
        INNER JOIN RO_T_COEFICIENTES_PRORRATEO B        
        ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO

        UNION ALL

        --REGISTROS DE PRORRATEO METODO 9--  
        SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,  
        CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,  
        CASE WHEN A.COD_PRORRATEO_2 = '4' THEN  
            CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))  
        ELSE  
            CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))  
        END SALDO_PRORRATEO,  
        A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO, ISNULL(B.NRO_SUCURS, A.NRO_SUCURS) NUM_SUCURSAL, 1 PRORRATEADO, A.ID_AA,  
        A.AMORTIZAR, A.AMORTIZADO FROM  
         (  
          SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,  
          CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO,  
          CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,  
          A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,  
          CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,  
          A.DESC_PRORRATEO, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM  
          (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '9'  
          AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A  
          INNER JOIN RO_T_COEFICIENTES_PRORRATEO B  
          ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO  
          WHERE A.EXCLUIR = 0  
        UNION ALL  
          SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,  
          CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO,  
          CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,  
          A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,  
          CASE WHEN NRO_SUCURS = 0 THEN '4' ELSE '' END COD_PRORRATEO_2,  
          A.DESC_PRORRATEO, B.NRO_SUCURS, A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM  
          (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '9'  
          AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL) A  
          INNER JOIN RO_T_COEFICIENTES_PRORRATEO B  
          ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO  
          WHERE A.EXCLUIR = 0  
          ) A  
        LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B  
        ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO  

        UNION ALL

     --REGISTROS DE PRORRATEO METODO 11--  
    SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,  
    CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,  
    CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,  
    A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, B.NRO_SUCURS, 1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM  
    (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '11'  
    AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZADO IS NULL) A  
    INNER JOIN RO_T_COEFICIENTES_PRORRATEO B  
    ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO  
    WHERE A.EXCLUIR = 0  
     UNION ALL  
    SELECT A.ID, @PERIODO PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,  
    CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,  
    CAST(CAST((CAST(A.SALDO AS DECIMAL(18,4))*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_PRORRATEO,  
    A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, NULL COD_PRORRATEO_2, A.DESC_PRORRATEO, B.NRO_SUCURS, 1 PRORRATEADO, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM  
    (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '11'  
    AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL) A  
    INNER JOIN RO_T_COEFICIENTES_PRORRATEO B  
    ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO  
    WHERE A.EXCLUIR = 0  

        UNION ALL

    --REGISTROS DE PRORRATEO METODO 12--
    SELECT A.ID, A.PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA,
    CAST(CAST(A.SALDO AS DECIMAL(18,4)) AS NUMERIC(38,7)) SALDO_ORIGEN,
    CASE WHEN A.COD_PRORRATEO_2 IN ('4', '11') THEN
        CAST(CAST((CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) * B.PARTICIPACION/100) AS DECIMAL(18,4)) AS NUMERIC(38,7))
    ELSE
        CAST(CAST(A.SALDO_PRORRATEO AS DECIMAL(18,4)) AS NUMERIC(38,7))
    END SALDO_PRORRATEO,
    A.DESC_LEYENDA, A.T_COMP, A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO, COD_PRORRATEO_2, A.DESC_PRORRATEO, ISNULL(B.NRO_SUCURS, A.NRO_SUCURS) NUM_SUCURSAL, 1 PRORRATEADO, A.ID_AA,
    A.AMORTIZAR, A.AMORTIZADO FROM
     (
      SELECT A.ID, A.PERIODO_ACTUAL PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,
      -- Convertir los cálculos a DECIMAL primero para evitar desbordamiento
      CAST(CAST((A.SALDO*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,
      A.DESC_LEYENDA, A.T_COMP,
      A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,
      CASE WHEN NRO_SUCURS = 0 THEN '4' WHEN NRO_SUCURS = 102 THEN '11' ELSE '' END COD_PRORRATEO_2,
      A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS,
      A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM
      (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '12'
      AND FECHA BETWEEN @DESDE AND @HASTA AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZADO IS NULL) A
      INNER JOIN RO_T_COEFICIENTES_PRORRATEO B ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO
       UNION ALL
      SELECT A.ID, @PERIODO PERIODO, A.MODULO, A.COD_AUXILIAR, A.FECHA, A.DESC_AUXILIAR, A.SECTOR, A.COD_CUENTA, A.DESC_CUENTA, A.SALDO,
      CAST(CAST((A.SALDO*B.PARTICIPACION/100) AS DECIMAL(18,4)) AS DECIMAL(18,4)) SALDO_PRORRATEO,
      A.DESC_LEYENDA, A.T_COMP,
      A.RAZON_SOCIAL, A.PROVEEDOR, A.N_COMP, A.IMPUTACIONES, A.COD_RUBRO, A.RUBRO_CONTABLE, A.COD_PRORRATEO,
      CASE WHEN NRO_SUCURS = 0 THEN '4' WHEN NRO_SUCURS = 102 THEN '11' ELSE '' END COD_PRORRATEO_2,
      A.DESC_PRORRATEO, A.NUM_SUCURSAL SUC_ORIG, B.NRO_SUCURS,
      A.EXCLUIR, A.ID_AA, A.AMORTIZAR, A.AMORTIZADO FROM
      (SELECT CAST(DATEPART(MONTH, FECHA) AS VARCHAR)+'-'+CAST(DATEPART(YEAR, FECHA) AS VARCHAR) PERIODO_ACTUAL, * FROM RO_T_INTEGRAL_TANGO_2 WHERE COD_PRORRATEO = '12'
      AND PERIODO = @PERIODO AND CONTROLADO = 1 AND EXCLUIR = 0 AND PRORRATEADO IS NULL AND AMORTIZAR IS NULL) A
      INNER JOIN RO_T_COEFICIENTES_PRORRATEO B ON A.PERIODO_ACTUAL = B.PERIODO AND A.COD_PRORRATEO = B.COD_PRORRATEO
     ) A
    LEFT JOIN RO_T_COEFICIENTES_PRORRATEO B
    ON A.PERIODO = B.PERIODO AND A.COD_PRORRATEO_2 = B.COD_PRORRATEO
    WHERE A.ID NOT IN (SELECT DISTINCT(ID) ID FROM RO_T_INTEGRAL_PRORRATEOS)

        ORDER BY ID;

        -- Punto de control: Registros insertados
        DECLARE @TOTAL_REGISTROS INT;
        SET @TOTAL_REGISTROS = (SELECT COUNT(*) FROM #TABLA_TEMPORAL_PR);

        IF @ID_PROCESO IS NOT NULL
        BEGIN
            EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                @ID_PROCESO = @ID_PROCESO,
                @ESTADO = 'EN_PROCESO',
                @PROGRESO = 60,
                @MENSAJE = 'Registros recopilados. Procesando...',
                @TOTAL_REGISTROS = @TOTAL_REGISTROS;
        END
          
        IF @TOTAL_REGISTROS > 0        
        BEGIN        
            -- Punto de control: Actualizando registros
            IF @ID_PROCESO IS NOT NULL
            BEGIN
                EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                    @ID_PROCESO = @ID_PROCESO,
                    @ESTADO = 'EN_PROCESO',
                    @PROGRESO = 70,
                    @MENSAJE = 'Actualizando registros...';
            END

            --ACTUALIZA EL ESTADO DEL GASTO A PRORRATEADO--        
            UPDATE RO_T_INTEGRAL_TANGO_2 SET PRORRATEADO = 1 WHERE ID IN (SELECT DISTINCT(ID) ID FROM #TABLA_TEMPORAL_PR);

            -- Punto de control: Insertando en tabla de prorrateos
            IF @ID_PROCESO IS NOT NULL
            BEGIN
                EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                    @ID_PROCESO = @ID_PROCESO,
                    @ESTADO = 'EN_PROCESO',
                    @PROGRESO = 80,
                    @MENSAJE = 'Insertando en tabla de prorrateos...';
            END
          
            --INSERTA EN LA TABLA FINAL DE PRORRATEOS--        
            INSERT INTO RO_T_INTEGRAL_PRORRATEOS        
            SELECT * FROM #TABLA_TEMPORAL_PR;

            -- Punto de control: Insertando en tabla integral final
            IF @ID_PROCESO IS NOT NULL
            BEGIN
                EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                    @ID_PROCESO = @ID_PROCESO,
                    @ESTADO = 'EN_PROCESO',
                    @PROGRESO = 90,
                    @MENSAJE = 'Insertando en tabla integral final...';
            END
             
            --INSERTA EN LA TABLA INTEGRAL FINAL--        
            INSERT INTO RO_T_INTEGRAL_FINAL        
            SELECT * FROM RO_T_INTEGRAL_PRORRATEOS WHERE ID IN (SELECT DISTINCT(ID) ID FROM #TABLA_TEMPORAL_PR) AND PERIODO = @PERIODO;
          
            --ELIMINA LA TABLA TEMPORAL--        
            DROP TABLE #TABLA_TEMPORAL_PR;

            -- Proceso completado
            IF @ID_PROCESO IS NOT NULL
            BEGIN
                EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                    @ID_PROCESO = @ID_PROCESO,
                    @ESTADO = 'COMPLETADO',
                    @PROGRESO = 100,
                    @MENSAJE = 'Prorrateo completado exitosamente',
                    @REGISTROS_PROCESADOS = @TOTAL_REGISTROS;
            END
          
        END        
        ELSE         
        BEGIN
            DROP TABLE #TABLA_TEMPORAL_PR;
            
            IF @ID_PROCESO IS NOT NULL
            BEGIN
                EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                    @ID_PROCESO = @ID_PROCESO,
                    @ESTADO = 'COMPLETADO',
                    @PROGRESO = 100,
                    @MENSAJE = 'No se encontraron registros para prorratear';
            END
            
            PRINT 0;
        END

    END TRY
    BEGIN CATCH
        -- Registrar error
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();
        
        IF @ID_PROCESO IS NOT NULL
        BEGIN
            EXEC RO_SP_ACTUALIZAR_PROGRESO_PROCESO 
                @ID_PROCESO = @ID_PROCESO,
                @ESTADO = 'ERROR',
                @MENSAJE = 'Error durante el prorrateo',
                @DETALLES_ERROR = @ErrorMessage;
        END
        
        -- Limpiar tabla temporal si existe
        IF OBJECT_ID('tempdb..#TABLA_TEMPORAL_PR') IS NOT NULL
            DROP TABLE #TABLA_TEMPORAL_PR;
        
        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
          
END

